version: 0.0
os: linux

files:
  - source: packages/hoppscotch-selfhost-web/dist/
    destination: /var/www/hoppscotch/
file_exists_behavior: OVERWRITE

permissions:
  - object: /var/www/hoppscotch
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: /bin/echo
      timeout: 30
      runas: root
      args:
        - "Before Install"
  AfterInstall:
    - location: /bin/echo
      timeout: 30
      runas: root
      args:
        - "After Install"
  ApplicationStart:
    - location: /bin/echo
      timeout: 30
      runas: root
      args:
        - "Application Start"
  ValidateService:
    - location: /bin/echo
      timeout: 30
      runas: root
      args:
        - "Validate Service"
